# Data Science Assignment 3 Day 3 Nov 11, 2020


In [1]:
#Question 1: Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [3]:
# Question 2: Accept two lists of 5 elements each from the user.
#Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [4]:
a=np.array([int(input()) for i in range(5)])
b=np.array([int(input()) for i in range(5)])
print(np.sort(np.concatenate((a,b))))

10
11
12
13
15
20
21
22
25
23
[10 11 12 13 15 20 21 22 23 25]


In [5]:
#Question 3: Write a code snippet to find the dimensions of a ndarray and its size.

In [6]:
arr=np.array([20,21,25,23,26])
print(arr.ndim)
print(arr.size)

1
5


In [7]:
#Question4: How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
#Hint: np.newaxis, np.expand_dims

In [17]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
a2 = a[np.newaxis, :]
a2.shape
#col_vector = a[:, np.newaxis]
#col_vector.shape
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [18]:
#Question 5: Consider two square numpy arrays. Stack them vertically and horizontally.
#Hint: Use vstack(), hstack()

In [19]:
a=np.array([[3,4,5],[7,8,9],[1,1,1]])
print(np.vstack(a))
print(np.hstack(a))

[[3 4 5]
 [7 8 9]
 [1 1 1]]
[3 4 5 7 8 9 1 1 1]


In [20]:
#Question 6: How to get unique items and counts of unique items?

In [21]:
a=np.arange(10,20)
print(np.unique(a,return_counts=True))

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))
